In [1]:
import numpy as np

In [9]:
help (np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

In [12]:
#Criação de um array 1D
l = [1,2,3]
x = np.array(l)

print (l)
print (x.shape)

print (type(x))

[1, 2, 3]
(3,)
<class 'numpy.ndarray'>


In [13]:
#Criação de um array 2D
l = [1,2], [3,4]
x = np.array(l)

print (l)
print (x.shape)

print (type(x))

([1, 2], [3, 4])
(2, 2)
<class 'numpy.ndarray'>


In [14]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [17]:
dim = (3,5)
x = np.zeros(dim,dtype=int)

print (x)
print (x.shape)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
(3, 5)


In [18]:
dim = (3,5)
x = np.ones(dim,dtype=int)

print (x)
print (x.shape)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
(3, 5)


In [21]:
np.linspace?

Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples to generate. Default is 50. Must be non-negative.
endpoint : bool, optional
    If True, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
retstep : 

In [22]:
#criação de valores denro de um intervalo

x_min, x_max = 5, 15
x = np.linspace(start=x_min, stop=x_max, num=6)

print (x)
print (x.shape)

[ 5.  7.  9. 11. 13. 15.]
(6,)


In [23]:
#matriz identidade

n = 4
x = np.eye(n)

print ("\n", x)
print (x.shape)


 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)


In [24]:
#valores aleatórios

x = np.random.random(size = (2,3))

print ("\n", x)
print (x.shape)


 [[0.96983702 0.14872697 0.99562593]
 [0.02875483 0.60482034 0.21584599]]
(2, 3)


## Indexação de arrays

In [27]:
x = np.linspace(start=10, stop = 100, num = 10, dtype = int)

print(x)
print(x.shape)

[ 10  20  30  40  50  60  70  80  90 100]
(10,)


In [28]:
print("1o:", x[0])
print("2o:", x[1])
print("Último:", x[9])
print("Últimoo:", x[-1])

1o: 10
2o: 20
Último: 100
Últimoo: 100


In [30]:
print("2 1os:", x[0:2])
print("2 1os:", x[:2])
print("2 últimos:", x[-2:])
print("2 últimos:", x[8:])

2 1os: [10 20]
2 1os: [10 20]
2 últimos: [ 90 100]
2 últimos: [ 90 100]


In [31]:
x = x.reshape(2,5)
x

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [33]:
print("linha 1 col 2", x[1,2])

linha 1 col 2 80
